service:
  name: ark-core-journeys
plugins:
  - serverless-stack-output
provider:
  name: aws
  stage: ${opt:env}

custom:
  output:
    handler: output.handler
    file: infrastructure-output.json
  dbparams:
    port: 5432
    name: core_journeys_${opt:env}
    dbuser: test_user
    dbpassword: test_password
    clustername: core-journeys-${opt:env}
  aws:
    vpc-id: vpc-9c5371f0
    gateway-ssl-cert-arn: arn:aws:acm:us-east-1:894231352815:certificate/0ebf2bf0-bab3-4070-b042-5e3a42929b70
    lambda-group-name: ${opt:lambdaGroupName}
    private-subnets:
      - subnet-99b842c3
      - subnet-905371fc
    public-subnets:
      - subnet-955371f9
      - subnet-5fec2a05
functions: # None - this is backing infrastructure only.

resources:
  Resources:
    ApolloGatewaySecurityGroup: ${file(resources/cf-stacks/security/gateway-security-group.yml)}
    ApolloGatewayLBSecurityGroup: ${file(resources/cf-stacks/security/gateway-lb-security-group.yml)}
    ApolloGatewayLoadBalancer: ${file(resources/cf-stacks/ec2/gateway-lb.yml)}
    ApolloGatewayInstance: ${file(resources/cf-stacks/ec2/gateway-instance.yml)}
    ApolloGatewayHTTPSListener: ${file(resources/cf-stacks/ec2/gateway-lb-https-listener.yml)}
    ApolloGatewayHTTPListener: ${file(resources/cf-stacks/ec2/gateway-lb-http-listener.yml)}
    ApolloGatewayTargetGroup: ${file(resources/cf-stacks/ec2/gateway-lb-target-group.yml)}
    ApolloGatewayLaunchTemplate: ${file(resources/cf-stacks/ec2/gateway-launch-template.yml)}
    # ApolloGatewayScalingPolicy: ${file(resources/cf-stacks/ec2/gateway-scaling-policy-template.yml)}
    LambdaSecurityGroup: ${file(resources/cf-stacks/lambdas/lambda-security-group-template.yml)}
    LambdaSecurityGroupIngress: ${file(resources/cf-stacks/lambdas/lambda-security-group-ingress-template.yml)}
    CoreDBCluster: ${file(resources/cf-stacks/db/jf-core-cluster.yml)}
    CoreDBMaster: ${file(resources/cf-stacks/db/master-instance.yml)}
    DBClusterParamGroup: ${file(resources/cf-stacks/db/param-group-cluster.yml)}
    DBInstanceParamGroup: ${file(resources/cf-stacks/db/param-group-instance.yml)}
    DBSubnetGroup: ${file(resources/cf-stacks/db/subnet-group.yml)}
  Outputs:
    ApolloGatewayLoadBalancer:
      Description: DNS Name for Apollo load balancer
      Value: !GetAtt ApolloGatewayLoadBalancer.DNSName
    LambdaSecurityGroupId:
      Description: "Security group Id for Lambda and RDS"
      Value: !GetAtt LambdaSecurityGroup.GroupId
    ConnectionString:
      Description: "Connection String"
      Value: !Join
        - ""
        - - "${self:custom.dbparams.dbuser}:${self:custom.dbparams.dbpassword}@"
          - !GetAtt CoreDBCluster.Endpoint.Address
          - ":"
          - !GetAtt CoreDBCluster.Endpoint.Port
          - "/${self:custom.dbparams.name}?schema=public"
