version: '3.8'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '9632:5432'
volumes:
  postgres:
