Type: AWS::EC2::SecurityGroupIngress
DependsOn: LambdaSecurityGroup
Properties:
  GroupId: !Ref LambdaSecurityGroup
  IpProtocol: tcp
  FromPort: ${self:custom.dbparams.port}
  ToPort: ${self:custom.dbparams.port}
