[install]
# Use exact versions from package.json
exact = true
# Use lockfile for consistent installs
frozen-lockfile = true
# Always generate a lockfile
no-lockfile = false
# Don't modify package.json on install
save = false
# Don't modify devDependencies
save-dev = false
# Don't modify dependencies
save-prod = false
# Don't modify optionalDependencies
save-optional = false
# Don't modify peerDependencies
save-peer = false

[install.cache]
# Enable the global cache
dir = ".bun"
# Enable caching
disable = false

[test]
# Use Jest compatibility layer
jest = true
# Enable coverage reporting
coverage = true
# Show test names
bail = true
# Use the same environment as Jest
environment = "node"

[debug]
# Enable source maps for debugging
sourcemap = true

[run]
# Enable watch mode for development
watch = false
# Enable hot module replacement
hot = true

[build]
# Entry points for the build
entrypoints = ["./src/main.ts"]
# Output directory
outdir = "dist"
# Minify output
minify = true
# Generate source maps
sourcemap = true

# [install.scopes]
# Allow workspace dependencies
# workspaces = true

[install.lockfile]
# Path to the lockfile
path = "bun.lock"

[install.registry]
# Use the official NPM registry
url = "https://registry.npmjs.org"
# Enable strict SSL
strict-ssl = true

[install.peer]
# Handle peer dependencies
resolve = true

[install.native]
# Trust specific native dependencies
sharp = true
canvas = true 