'base_url': 'https://api.crowdin.com'
'preserve_hierarchy': true
'project_id_env': CROWDIN_PROJECT_ID
'api_token_env': CROWDIN_PERSONAL_TOKEN
'pull_request_title': 'chore: new crowdin translations'
'commit_message': 'chore: new translations %original_file_name% %language%'
'append_commit_message': false
'pull_request_labels': ['effort: 1', 'priority: soon', 'type: chore']
'pull_request_assignees': ['crowdin-bot']
'files':
  [
    {
      'source': '/libs/locales/en/*.json',
      'translation': '/libs/locales/%locale%/%original_file_name%',
      'type': 'i18next_json',
      'skip_untranslated_files': true
    }
  ]
