'base_url': 'https://api.crowdin.com'
'preserve_hierarchy': true
'pull_request_title': 'chore: new crowdin translations'
'commit_message': 'chore: new translations %original_file_name% %language%'
'append_commit_message': false
'pull_request_labels': ['effort: 1', 'priority: soon', 'type: chore']
'files':
  [
    {
      'source': '/libs/locales/en/*.json',
      'translation': '/libs/locales/%two_letters_code%/%original_file_name%',
      'type': 'i18next_json'
    }
  ]
