'base_url': 'https://api.crowdin.com'
'preserve_hierarchy': true
'project_id_env': CROWDIN_PROJECT_ID
'api_token_env': CROWDIN_PERSONAL_TOKEN
'files':
  [
    {
      'source': '/libs/locales/en/*.json',
      'translation': '/libs/locales/%two_letters_code%/%original_file_name%',
      'type': 'i18next_json'
    }
  ]
