journeys-serve: nx serve api-journeys
journeys-watcher: nx watcher api-journeys
users-serve: nx serve api-users
users-watcher: nx watcher api-users
languages-serve: nx serve api-languages
languages-watcher: nx watcher api-languages
videos-serve: nx serve api-videos
videos-watcher: nx watcher api-videos
gateway: nx serve api-gateway
