journeys-serve: nx serve api-journeys
journeys-watcher: nx watcher api-journeys
media-serve: nx serve api-media
media-watcher: nx watcher api-media
tags-serve: nx serve api-tags
tags-watcher: nx watcher api-tags
users-serve: nx serve api-users
users-watcher: nx watcher api-users
languages-serve: nx serve api-languages
languages-watcher: nx watcher api-languages
videos-serve: nx serve api-videos
videos-watcher: nx watcher api-videos
mq-serve: nx serve mq
gateway: nx serve api-gateway
