/**
 * Pure helpers for `scripts/deploy.ts`: which live bindings a deploy has to
 * carry over, and the config that carries them.
 *
 * `wrangler deploy` uploads exactly the bindings in its config and drops the
 * rest. api-media adds one `KV_*` binding per short-link domain through the
 * Cloudflare API, so without this every deploy would undo them.
 *
 * Ownership: `KV_*` bindings belong to api-media and are carried over;
 * everything else belongs to `wrangler.toml` and is never carried.
 */

export interface LiveBinding {
  name: string
  type: string
  namespace_id?: string
}

export interface CarriedKvBinding {
  binding: string
  id: string
}

const OWNED_BY_API_MEDIA = /^KV_[A-Z0-9_]+$/

/** Live `KV_*` namespace bindings the config for this environment does not declare. */
export function bindingsToCarryOver(
  declaredBindings: string[],
  liveBindings: LiveBinding[]
): CarriedKvBinding[] {
  return liveBindings.flatMap(({ name, type, namespace_id: id }) =>
    type === 'kv_namespace' &&
    id != null &&
    OWNED_BY_API_MEDIA.test(name) &&
    !declaredBindings.includes(name)
      ? [{ binding: name, id }]
      : []
  )
}

/**
 * Drops the top-level `[[kv_namespaces]]` tables for the given bindings. The
 * top-level (dev) section declares per-domain namespaces for tests and
 * `wrangler dev`; a stage or prod deploy never uses them, and wrangler warns
 * about each one that the deployed environment does not also declare.
 */
function withoutTopLevelKvNamespaces(
  wranglerToml: string,
  bindings: string[]
): string {
  const kept: string[] = []
  const lines = wranglerToml.split('\n')
  for (let index = 0; index < lines.length; index++) {
    if (lines[index].trim() !== '[[kv_namespaces]]') {
      kept.push(lines[index])
      continue
    }
    let end = index + 1
    while (
      end < lines.length &&
      lines[end].trim() !== '' &&
      !lines[end].trimStart().startsWith('[')
    )
      end++
    const table = lines.slice(index, end)
    const binding = table
      .map((line) => /^\s*binding\s*=\s*"([^"]+)"/.exec(line)?.[1])
      .find((name) => name != null)
    if (binding == null || !bindings.includes(binding)) kept.push(...table)
    index = end - 1
  }
  return kept.join('\n')
}

/**
 * The config a deploy uses: `wrangler.toml` without the dev-only top-level
 * namespaces, plus one `[[env.<env>.kv_namespaces]]` block per carried binding
 * appended at the end (an array of tables may be continued anywhere in a TOML
 * file).
 */
export function renderDeployConfig(
  wranglerToml: string,
  environment: string,
  carried: CarriedKvBinding[],
  devOnlyBindings: string[] = []
): string {
  const base = withoutTopLevelKvNamespaces(wranglerToml, devOnlyBindings)
  if (carried.length === 0) return base

  const blocks = carried.map(
    ({ binding, id }) =>
      `[[env.${environment}.kv_namespaces]]\nbinding = ${JSON.stringify(binding)}\nid = ${JSON.stringify(id)}\n`
  )
  return [
    base.trimEnd(),
    '',
    '# ---------------------------------------------------------------------------',
    '# Generated by scripts/deploy.ts: per-domain KV bindings api-media added to',
    '# the live Worker through the Cloudflare API. Not part of wrangler.toml.',
    '# ---------------------------------------------------------------------------',
    '',
    blocks.join('\n')
  ].join('\n')
}
