## Configuration for external-dns
sources:
  - service
  - ingress

# Set provider name to aws
provider:
  name: aws

# Environment variables will be used for AWS credentials
env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: externaldns-aws-credentials
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: externaldns-aws-credentials
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_REGION
    value: 'us-east-2'
  - name: AWS_DEFAULT_REGION
    value: 'us-east-2'

# Set log level to debug
logLevel: debug

# AWS specific configuration
aws:
  region: 'us-east-2'
  zoneType: 'public'
  batchChangeSize: 1000
  preferCNAME: true
  evaluateTargetHealth: true
  assumeRole:
    enabled: false

# Processing only specific domains
domainFilters:
  - central.jesusfilm.org

# Specify the Route53 hosted zone ID
zoneIdFilters:
  - Z06687872LMUIKS0Y291P

# Define args to pass to external-dns
extraArgs:
  - --ingress-class=nginx
  - --txt-prefix=external-dns-
  - --zone-id-filter=Z06687872LMUIKS0Y291P
  - --domain-filter=central.jesusfilm.org

policy: 'upsert-only'
registry: 'txt'
txtOwnerId: 'external-dns-production'

# Annotations on pods to identify this instance
podAnnotations:
  environment: 'production'

# RBAC configuration
rbac:
  create: true

# Service account configuration
serviceAccount:
  create: true
  # Remove explicit name to let the Helm chart use its default name
  # name: 'external-dns'
