## Configuration for external-dns
sources:
  - service
  - ingress

provider: aws

aws:
  region: 'us-east-2'
  # Credentials will be provided through Doppler's created secret
  credentials:
    secretName: 'externaldns-aws-credentials'
    secretNamespace: 'default'
    accessKey: 'AWS_ACCESS_KEY_ID'
    secretKey: 'AWS_SECRET_ACCESS_KEY'
  # Only look at public hosted zones
  zoneType: 'public'

# Processing only specific domains
domainFilters:
  - 'central.jesusfilm.org'

policy: 'upsert-only'
registry: 'txt'
txtOwnerId: 'external-dns-production'

# Annotations on pods to identify this instance
podAnnotations:
  environment: 'production'

rbac:
  create: true

serviceAccount:
  create: true
  name: 'external-dns'
  automountServiceAccountToken: true
