apiVersion: batch/v1
kind: CronJob
metadata:
  name: arangodb-s3-backup-cronjob
spec:
  schedule: '0 3 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: arangodb-s3-backup
              image: 894231352815.dkr.ecr.us-east-2.amazonaws.com/jfp-arangodb-s3-backup:latest
              imagePullPolicy: IfNotPresent
              command:
                - arangobackup create --server.endpoint $DATABSE_URL --server.authentication true --server.database $DATABASE_DB --server.username $DATABASE_USER --server.password $DATABASE_PASS
                - aws s3 cp . $S3_BUCKET
              envFrom:
                - secretRef:
                    name: doppler-arangodb-s3-backup-secret-prd
          restartPolicy: OnFailure
