apiVersion: batch/v1
kind: CronJob
metadata:
  name: arangodb-s3-backup-cronjob
spec:
  schedule: '0 3 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            type: api
          containers:
            - name: arangodb-s3-backup
              image: 894231352815.dkr.ecr.us-east-2.amazonaws.com/jfp-arangodb-s3-backup:latest
              imagePullPolicy: IfNotPresent
              command:
                - ./backup.sh
              envFrom:
                - secretRef:
                    name: doppler-arangodb-s3-backup-secret-prd
          restartPolicy: Never
