project: default
source:
  repoURL: https://github.com/JesusFilm/core
  path: infrastructure/kube/aws-load-balancer-controller
  targetRevision: main
  helm:
    valueFiles:
      - values.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: kube-system
