project: default
source:
  repoURL: https://github.com/JesusFilm/core
  path: infrastructure/kube/cert-manager
  targetRevision: main
  helm:
    valueFiles:
      - values.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: cert-manager
