apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doppler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JesusFilm/core
    path: infrastructure/kube/doppler
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: doppler-operator-system
