project: default
source:
  repoURL: https://github.com/JesusFilm/core
  path: infrastructure/kube/metrics-server
  targetRevision: main
destination:
  server: https://kubernetes.default.svc
  namespace: kube-system
