project: default
source:
  repoURL: https://github.com/JesusFilm/core
  path: infrastructure/kube/snapscheduler
  targetRevision: main
destination:
  server: https://kubernetes.default.svc
  namespace: snapscheduler
