apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: clickhouse-gp3-snapshot
spec:
  volumeSnapshotClassName: clickhouse-gp3-snapshotclass
  source:
    persistentVolumeClaimName: plausible-analytics-clickhouse-data-plausible-analytics-clickhouse-0
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: clickhouse-gp3-replica-snapshot
spec:
  volumeSnapshotClassName: clickhouse-gp3-snapshotclass
  source:
    persistentVolumeClaimName: plausible-analytics-clickhouse-replica-data-plausible-analytics-clickhouse-replica-0
