import './customDomain'
import './customDomainDelete.mutation'
import './customDomainUpdate.mutation'
import './customDomainCreate.mutation'
import './customDomains.query'
import './inputs'
import './customDomain.query'
