import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { ReactNode } from 'react'

import { ThemeProvider } from '@core/shared/ui/ThemeProvider'
import { ThemeMode, ThemeName } from '@core/shared/ui/themes'

import './global.css'
import { ApolloWrapper } from '../libs/apolloClient/apolloWrapper'

export const metadata = {
  title: 'Welcome to watch-new',
  description: 'Generated by create-nx-workspace'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): ReactNode {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;800&family=Open+Sans&display=swap"
          rel="stylesheet"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/watch/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/watch/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/watch/favicon-32x32.png"
        />
        <link rel="manifest" href="/watch/site.webmanifest" />
      </head>
      <body>
        <ApolloWrapper>
          <AppRouterCacheProvider>
            <ThemeProvider
              themeName={ThemeName.website}
              themeMode={ThemeMode.light}
            >
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
