resource "aws_launch_template" "tfer--eks-44c0982c-e213-b4b9-339a-f2fe936b5f86" {
  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      delete_on_termination = "true"
      iops                  = "0"
      throughput            = "0"
      volume_size           = "20"
      volume_type           = "gp2"
    }
  }

  default_version         = "1"
  disable_api_stop        = "false"
  disable_api_termination = "false"

  iam_instance_profile {
    name = "eks-44c0982c-e213-b4b9-339a-f2fe936b5f86"
  }

  image_id      = "ami-0bf61ea17cec89b3a"
  instance_type = "t3.medium"

  metadata_options {
    http_put_response_hop_limit = "2"
  }

  name = "eks-44c0982c-e213-b4b9-339a-f2fe936b5f86"

  network_interfaces {
    device_index       = "0"
    ipv4_address_count = "0"
    ipv4_prefix_count  = "0"
    ipv6_address_count = "0"
    ipv6_prefix_count  = "0"
    network_card_index = "0"
    security_groups    = ["sg-096321fc5ad4991e1"]
  }

  tags = {
    "eks:cluster-name"   = "JesusFilm-core"
    "eks:nodegroup-name" = "API"
  }

  tags_all = {
    "eks:cluster-name"   = "JesusFilm-core"
    "eks:nodegroup-name" = "API"
  }

  user_data = "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvbWl4ZWQ7IGJvdW5kYXJ5PSIvLyIKCi0tLy8KQ29udGVudC1UeXBlOiB0ZXh0L3gtc2hlbGxzY3JpcHQ7IGNoYXJzZXQ9InVzLWFzY2lpIgojIS9iaW4vYmFzaApzZXQgLWV4CkI2NF9DTFVTVEVSX0NBPUxTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVU0xZWtORFFXTXJaMEYzU1VKQlowbENRVVJCVGtKbmEzRm9hMmxIT1hjd1FrRlJjMFpCUkVGV1RWSk5kMFZSV1VSV1VWRkVSWGR3Y21SWFNtd0tZMjAxYkdSSFZucE5RalJZUkZSSmVVMUVXWGRPUkVsM1RVUlJkMDVzYjFoRVZFMTVUVVJaZDAxVVNYZE5SRkYzVG14dmQwWlVSVlJOUWtWSFFURlZSUXBCZUUxTFlUTldhVnBZU25WYVdGSnNZM3BEUTBGVFNYZEVVVmxLUzI5YVNXaDJZMDVCVVVWQ1FsRkJSR2RuUlZCQlJFTkRRVkZ2UTJkblJVSkJUblJuQ2pOcVUxTXdObmRuYW1aNEswcGxWSGRtVWs1a1RETm5jRUZsZW1aRk5WQmxVek4wTkV0UWRXSXdVMWw1TWtZNFpVWkdkMWhZY1doMVZqUTRRVEJ2V2xrS1ozVlNSblZ2YzBkQlJ6bHdZbHBaTlRseFZrMUtNMjVTWTBoc1puSnBXRE56V1hOcVFsWTBkRmhqYzFkV1EzbG9VbFF3ZFhGcmRqaHVka3hwWTFGd1RBb3JjRnBOVFVSMGVFSXliR3cyY0VGUlJYVTJiSGRZYUhGU1FVNTJUR0ZrTTNCVVZYTkJibE5rY2l0eFRUTm1URFpJUXpCd05VSktVRXcxVG5obGJrZEhDbFV2VDNZeWJUQnViMWxxWm14S2FYQkNaRzlwU0ZVelFtZEhTWFJ4ZVRFNWVqbDVkMDR6U0c1QmVGbG1RVWRqWm1Sc2F6aHlNR1ZqYWtKallrNUJTVVVLVTFwclkwTkJUemRwZVZKaFVqZ3dPVzlpTmpsakswTXhha2RRT0Voak9FOUtTV0pFTHpGUFMwZHhNMDQzUWpCQmQwNW1OMGswVkVGUWVXa3pXSEIwUlFwc2JtcERla2NyZWpOTFVuaFZVRU5yWnl0TlEwRjNSVUZCWVU1RFRVVkJkMFJuV1VSV1VqQlFRVkZJTDBKQlVVUkJaMHRyVFVFNFIwRXhWV1JGZDBWQ0NpOTNVVVpOUVUxQ1FXWTRkMGhSV1VSV1VqQlBRa0paUlVaSVMxVktaelF4ZVdWdFVDOTROM2N5VmpNeFVFZHZSR3hJZUVOTlFUQkhRMU54UjFOSllqTUtSRkZGUWtOM1ZVRkJORWxDUVZGRVlVWm5UMHBsTUhOSmFHNU9lbTQ1YTJaTk1EbENNVWRUWnk5aFZDdERiVEpXTkVoaWMyWm5jbU5zUTJaSWFHRmtkUXBWWlVOMFduYzVOVTlXUmxod1NWWTNZVGh5ZG5BMFkwc3JVV1l5Wm1oeU1uTjJZVXcxWW01VmEwaDJPV1ZJTlZGbk5uRjFXRFJuVGxSUWRFeGlaV2RoQ2pWeFdHRnFkSE5WVlZOTldtUllWSGN6TjBSclZHMW9NVWw1Y25wYVNYTkdhemhVTjJSaVNWbElSM1IxTkZsdVprTlRlR0YzY1ZaNmJqazRZazFxVDBvS2VXSklieXRwT0VFelZIcEpXRmRTVURSSmRrWTBZbU5GUlVwWVRsbzVkemhpVkN0NFQzVnRSMWhKVFcwek5HWjZjMVEwUkVZdmRXZEZOakkyVlhVNGJRcFZURkJQT0VaUE9Fd3ZUbnBuTDNKMVZHNU5PRmRFWTFOTlExQk5ibTE0VkRZNGNFY3phV2hMUkRkSmMyTjBRa0ZZTW1GNlpTOTVNRFpGV1RkRlFrbzFDblJSVDJzclQyRlVZVmhLU2xJNVdqTlhPR1Z4Vm1sYVpXOVBkVFJZTUZSUVFteG5XUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09CkFQSV9TRVJWRVJfVVJMPWh0dHBzOi8vNTRBMjQyRTc4RTQzNTUzRTI1NzQxNTg1MjdBQkUzRTYuZ3I3LnVzLWVhc3QtMi5la3MuYW1hem9uYXdzLmNvbQpLOFNfQ0xVU1RFUl9ETlNfSVA9MTAuMTAwLjAuMTAKL2V0Yy9la3MvYm9vdHN0cmFwLnNoIEplc3VzRmlsbS1jb3JlIC0ta3ViZWxldC1leHRyYS1hcmdzICctLW5vZGUtbGFiZWxzPWVrcy5hbWF6b25hd3MuY29tL25vZGVncm91cC1pbWFnZT1hbWktMGJmNjFlYTE3Y2VjODliM2EsZWtzLmFtYXpvbmF3cy5jb20vY2FwYWNpdHlUeXBlPU9OX0RFTUFORCxla3MuYW1hem9uYXdzLmNvbS9ub2RlZ3JvdXA9QVBJLHR5cGU9YXBpIC0tbWF4LXBvZHM9MTcnIC0tYjY0LWNsdXN0ZXItY2EgJEI2NF9DTFVTVEVSX0NBIC0tYXBpc2VydmVyLWVuZHBvaW50ICRBUElfU0VSVkVSX1VSTCAtLWRucy1jbHVzdGVyLWlwICRLOFNfQ0xVU1RFUl9ETlNfSVAgLS11c2UtbWF4LXBvZHMgZmFsc2UKCi0tLy8tLQ=="
}

resource "aws_launch_template" "tfer--eks-acc0982c-86db-4719-77b5-b8974aeb2772" {
  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      delete_on_termination = "true"
      iops                  = "0"
      throughput            = "0"
      volume_size           = "20"
      volume_type           = "gp2"
    }
  }

  default_version         = "1"
  disable_api_stop        = "false"
  disable_api_termination = "false"

  iam_instance_profile {
    name = "eks-acc0982c-86db-4719-77b5-b8974aeb2772"
  }

  image_id      = "ami-0bf61ea17cec89b3a"
  instance_type = "i3.large"

  metadata_options {
    http_put_response_hop_limit = "2"
  }

  name = "eks-acc0982c-86db-4719-77b5-b8974aeb2772"

  network_interfaces {
    device_index       = "0"
    ipv4_address_count = "0"
    ipv4_prefix_count  = "0"
    ipv6_address_count = "0"
    ipv6_prefix_count  = "0"
    network_card_index = "0"
    security_groups    = ["sg-096321fc5ad4991e1"]
  }

  tags = {
    "eks:cluster-name"   = "JesusFilm-core"
    "eks:nodegroup-name" = "ArangoDB"
  }

  tags_all = {
    "eks:cluster-name"   = "JesusFilm-core"
    "eks:nodegroup-name" = "ArangoDB"
  }

  user_data = "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvbWl4ZWQ7IGJvdW5kYXJ5PSIvLyIKCi0tLy8KQ29udGVudC1UeXBlOiB0ZXh0L3gtc2hlbGxzY3JpcHQ7IGNoYXJzZXQ9InVzLWFzY2lpIgojIS9iaW4vYmFzaApzZXQgLWV4CkI2NF9DTFVTVEVSX0NBPUxTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVU0xZWtORFFXTXJaMEYzU1VKQlowbENRVVJCVGtKbmEzRm9hMmxIT1hjd1FrRlJjMFpCUkVGV1RWSk5kMFZSV1VSV1VWRkVSWGR3Y21SWFNtd0tZMjAxYkdSSFZucE5RalJZUkZSSmVVMUVXWGRPUkVsM1RVUlJkMDVzYjFoRVZFMTVUVVJaZDAxVVNYZE5SRkYzVG14dmQwWlVSVlJOUWtWSFFURlZSUXBCZUUxTFlUTldhVnBZU25WYVdGSnNZM3BEUTBGVFNYZEVVVmxLUzI5YVNXaDJZMDVCVVVWQ1FsRkJSR2RuUlZCQlJFTkRRVkZ2UTJkblJVSkJUblJuQ2pOcVUxTXdObmRuYW1aNEswcGxWSGRtVWs1a1RETm5jRUZsZW1aRk5WQmxVek4wTkV0UWRXSXdVMWw1TWtZNFpVWkdkMWhZY1doMVZqUTRRVEJ2V2xrS1ozVlNSblZ2YzBkQlJ6bHdZbHBaTlRseFZrMUtNMjVTWTBoc1puSnBXRE56V1hOcVFsWTBkRmhqYzFkV1EzbG9VbFF3ZFhGcmRqaHVka3hwWTFGd1RBb3JjRnBOVFVSMGVFSXliR3cyY0VGUlJYVTJiSGRZYUhGU1FVNTJUR0ZrTTNCVVZYTkJibE5rY2l0eFRUTm1URFpJUXpCd05VSktVRXcxVG5obGJrZEhDbFV2VDNZeWJUQnViMWxxWm14S2FYQkNaRzlwU0ZVelFtZEhTWFJ4ZVRFNWVqbDVkMDR6U0c1QmVGbG1RVWRqWm1Sc2F6aHlNR1ZqYWtKallrNUJTVVVLVTFwclkwTkJUemRwZVZKaFVqZ3dPVzlpTmpsakswTXhha2RRT0Voak9FOUtTV0pFTHpGUFMwZHhNMDQzUWpCQmQwNW1OMGswVkVGUWVXa3pXSEIwUlFwc2JtcERla2NyZWpOTFVuaFZVRU5yWnl0TlEwRjNSVUZCWVU1RFRVVkJkMFJuV1VSV1VqQlFRVkZJTDBKQlVVUkJaMHRyVFVFNFIwRXhWV1JGZDBWQ0NpOTNVVVpOUVUxQ1FXWTRkMGhSV1VSV1VqQlBRa0paUlVaSVMxVktaelF4ZVdWdFVDOTROM2N5VmpNeFVFZHZSR3hJZUVOTlFUQkhRMU54UjFOSllqTUtSRkZGUWtOM1ZVRkJORWxDUVZGRVlVWm5UMHBsTUhOSmFHNU9lbTQ1YTJaTk1EbENNVWRUWnk5aFZDdERiVEpXTkVoaWMyWm5jbU5zUTJaSWFHRmtkUXBWWlVOMFduYzVOVTlXUmxod1NWWTNZVGh5ZG5BMFkwc3JVV1l5Wm1oeU1uTjJZVXcxWW01VmEwaDJPV1ZJTlZGbk5uRjFXRFJuVGxSUWRFeGlaV2RoQ2pWeFdHRnFkSE5WVlZOTldtUllWSGN6TjBSclZHMW9NVWw1Y25wYVNYTkdhemhVTjJSaVNWbElSM1IxTkZsdVprTlRlR0YzY1ZaNmJqazRZazFxVDBvS2VXSklieXRwT0VFelZIcEpXRmRTVURSSmRrWTBZbU5GUlVwWVRsbzVkemhpVkN0NFQzVnRSMWhKVFcwek5HWjZjMVEwUkVZdmRXZEZOakkyVlhVNGJRcFZURkJQT0VaUE9Fd3ZUbnBuTDNKMVZHNU5PRmRFWTFOTlExQk5ibTE0VkRZNGNFY3phV2hMUkRkSmMyTjBRa0ZZTW1GNlpTOTVNRFpGV1RkRlFrbzFDblJSVDJzclQyRlVZVmhLU2xJNVdqTlhPR1Z4Vm1sYVpXOVBkVFJZTUZSUVFteG5XUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09CkFQSV9TRVJWRVJfVVJMPWh0dHBzOi8vNTRBMjQyRTc4RTQzNTUzRTI1NzQxNTg1MjdBQkUzRTYuZ3I3LnVzLWVhc3QtMi5la3MuYW1hem9uYXdzLmNvbQpLOFNfQ0xVU1RFUl9ETlNfSVA9MTAuMTAwLjAuMTAKL2V0Yy9la3MvYm9vdHN0cmFwLnNoIEplc3VzRmlsbS1jb3JlIC0ta3ViZWxldC1leHRyYS1hcmdzICctLW5vZGUtbGFiZWxzPWVrcy5hbWF6b25hd3MuY29tL25vZGVncm91cC1pbWFnZT1hbWktMGJmNjFlYTE3Y2VjODliM2EsZWtzLmFtYXpvbmF3cy5jb20vY2FwYWNpdHlUeXBlPU9OX0RFTUFORCxla3MuYW1hem9uYXdzLmNvbS9ub2RlZ3JvdXA9QXJhbmdvREIsdHlwZT1kYXRhYmFzZSAtLW1heC1wb2RzPTI5JyAtLWI2NC1jbHVzdGVyLWNhICRCNjRfQ0xVU1RFUl9DQSAtLWFwaXNlcnZlci1lbmRwb2ludCAkQVBJX1NFUlZFUl9VUkwgLS1kbnMtY2x1c3Rlci1pcCAkSzhTX0NMVVNURVJfRE5TX0lQIC0tdXNlLW1heC1wb2RzIGZhbHNlCgotLS8vLS0="
}
