// This file is generated automatically.
// Do not edit it manually.
import { Subjects } from '@casl/prisma'

import {
  Action, 
  Block, 
  ChatButton, 
  CustomDomain, 
  Event, 
  Host, 
  Integration, 
  Journey, 
  JourneyCollection, 
  JourneyCollectionJourneys, 
  JourneyCustomizationField, 
  JourneyEventsExportLog, 
  JourneyNotification, 
  JourneyProfile, 
  JourneyTag, 
  JourneyTheme, 
  JourneyVisitor, 
  JourneysEmailPreference, 
  QrCode, 
  Team, 
  UserInvite, 
  UserJourney, 
  UserRole, 
  UserTeam, 
  UserTeamInvite, 
  Visitor
} from '.prisma/api-journeys-client'

export type PrismaSubjects = Subjects<{
  Action: Action, 
  Block: Block, 
  ChatButton: ChatButton, 
  CustomDomain: CustomDomain, 
  Event: Event, 
  Host: Host, 
  Integration: Integration, 
  Journey: Journey, 
  JourneyCollection: JourneyCollection, 
  JourneyCollectionJourneys: JourneyCollectionJourneys, 
  JourneyCustomizationField: JourneyCustomizationField, 
  JourneyEventsExportLog: JourneyEventsExportLog, 
  JourneyNotification: JourneyNotification, 
  JourneyProfile: JourneyProfile, 
  JourneyTag: JourneyTag, 
  JourneyTheme: JourneyTheme, 
  JourneyVisitor: JourneyVisitor, 
  JourneysEmailPreference: JourneysEmailPreference, 
  QrCode: QrCode, 
  Team: Team, 
  UserInvite: UserInvite, 
  UserJourney: UserJourney, 
  UserRole: UserRole, 
  UserTeam: UserTeam, 
  UserTeamInvite: UserTeamInvite, 
  Visitor: Visitor
}>