apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::410965620680:role/terraform-eks-node-prod
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::410965620680:user/JfmGithubUser 
      username: JfmGithubUser 
      groups: 
        - system:masters
    - userarn: arn:aws:iam::410965620680:user/mike.allison
      username: mike.allison
      groups:
        - system:masters
