apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-auth-stage
  namespace: default
  labels:
    app.kubernetes.io/name: aws-auth
    app.kubernetes.io/part-of: eks
    environment: stage
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  source:
    repoURL: https://github.com/JesusFilm/core.git
    targetRevision: stage
    path: infrastructure/kube/aws-auth/stage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true


