project: default
source:
  repoURL: https://github.com/JesusFilm/core
  path: infrastructure/kube/aws-ebs-csi-driver
  targetRevision: stage
  helm:
    valueFiles:
      - values-stage.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: kube-system
