project: default
source:
  repoURL: https://github.com/JesusFilm/core
  path: infrastructure/kube/datadog-operator
  targetRevision: stage
  helm:
    valueFiles:
      - values-stage.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    enabled: true
