-- AlterTable
ALTER TABLE "BibleCitation" ALTER COLUMN "chapterStart" SET DEFAULT -1,
ALTER COLUMN "chapterEnd" SET DEFAULT -1,
ALTER COLUMN "verseStart" SET DEFAULT -1,
ALTER COLUMN "verseEnd" SET DEFAULT -1;
