import './inputs'
import './journeysPlausibleStatsAggregate.query'
import './journeysPlausibleStatsBreakdown.query'
import './journeysPlausibleStatsRealtimeVisitors.query'
import './journeysPlausibleStatsTimeseries.query'
import './templatePlausibleStatsBreakdown.query'
import './plausible'
