apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-plausible # DopplerSecret Name
  namespace: doppler-operator-system
spec:
  tokenSecret: # Kubernetes service token secret (namespace defaults to doppler-operator-system)
    name: doppler-token-secret
  project: plausible
  config: prd
  managedSecret: # Kubernetes managed secret (will be created if does not exist)
    name: plausible-prod
    namespace: default # Should match the namespace of deployments that will use the secret
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: externaldns-aws-credentials-prod
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
  project: kubernetes
  config: prod
  managedSecret:
    name: externaldns-aws-credentials
    namespace: default
