export const STEP_NODE_CARD_WIDTH = 200
export const STEP_NODE_CARD_HEIGHT = 76
export const STEP_NODE_HEIGHT = 152
export const STEP_NODE_WIDTH_GAP = 200
export const STEP_NODE_HEIGHT_GAP = 50
export const STEP_NODE_WIDTH = 216

export const NODE_EXTRA_DETECTION_WIDTH = 30

export const ACTION_BUTTON_HEIGHT = 27

export const HANDLE_DIAMETER = 6
export const HANDLE_BORDER_WIDTH = 2
export const HANDLE_WITH_BORDER_DIAMETER =
  HANDLE_DIAMETER + HANDLE_BORDER_WIDTH + HANDLE_BORDER_WIDTH
