name: API push build
on:
  push:
    branches:
      - main
      - stage
      - arangodb-cloud-deploy
jobs:
  api-journeys: 
    uses: JesusFilm/core/.github/workflows/api-deploy-worker.yml@arangodb-cloud-deploy
    with:
      name: api-journeys
      repository: jfp-api-journeys
    secrets:
      ARANGODB_URL: ${{ secrets.ARANGODB_URL }}
      ARANGODB_USER: ${{ secrets.ARANGODB_USER }}
      ARANGODB_PASS: ${{ secrets.ARANGODB_PASS }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  api-users:
    uses: JesusFilm/core/.github/workflows/api-deploy-worker.yml@arangodb-cloud-deploy
    with:
      name: api-users
      repository: jfp-api-users
    secrets:
      ARANGODB_URL: ${{ secrets.ARANGODB_URL }}
      ARANGODB_USER: ${{ secrets.ARANGODB_USER }}
      ARANGODB_PASS: ${{ secrets.ARANGODB_PASS }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

  api-gateway:
    needs: [api-journeys, api-users]
    uses: JesusFilm/core/.github/api-deploy-worker.yml@arangodb-cloud-deploy
    with:
      name: api-gateway
      repository: jfp-api-gateway
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
