name: API Deployment

on:
  workflow_call:
    secrets:
      AWS_DEFAULT_REGION:
        required: true
      JFP_AWS_ACCESS_KEY_ID:
        required: true
      JFP_AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build-and-deploy:
    environment: Production
    env:
      IMAGE_TAG: ${{ github.sha }}
    runs-on: blacksmith-2vcpu-ubuntu-2204
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Node Version
        id: node-version
        run: echo "version=$(node -v)" >> $GITHUB_OUTPUT

      - name: Mount NPM Cache
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-${{ steps.node-version.outputs.version }}-npm-cache
          path: ~/.npm
      - name: Mount node_modules
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-${{ steps.node-version.outputs.version }}-node-modules
          path: ./node_modules

      - name: NPM Install
        run: npm install --silent
      - name: Get affected apps
        run: |
          echo "apps=$(npx ts-node tools/scripts/affected-apps.ts --projects apis/api-*)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        id: affected-apps
      #ECS Deployment
      - name: Configure ECS AWS credentials
        if: contains(steps.affected-apps.outputs.apps, 'api-gateway')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.JFP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.JFP_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        if: contains(steps.affected-apps.outputs.apps, 'api-gateway')
        id: login-ecr-ecs
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        if: contains(steps.affected-apps.outputs.apps, 'api-gateway')
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to Amazon ECR
        if: contains(steps.affected-apps.outputs.apps, 'api-gateway')
        id: build-image-ecs
        uses: useblacksmith/build-push-action@v1
        with:
          context: .
          file: apis/api-gateway/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr-ecs.outputs.registry }}/jfp-api-gateway-stage:${{ env.IMAGE_TAG }}
            ${{ steps.login-ecr-ecs.outputs.registry }}/jfp-api-gateway-stage:latest
          build-args: |
            SERVICE_VERSION=${{ env.IMAGE_TAG }}

      - name: Set image output
        if: contains(steps.affected-apps.outputs.apps, 'api-gateway')
        run: |
          echo "image=${{ steps.login-ecr-ecs.outputs.registry }}/jfp-api-gateway-stage:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      - name: Restart task definition
        if: contains(steps.affected-apps.outputs.apps, 'api-gateway')
        run: |
          aws ecs update-service --force-new-deployment --service api-gateway-stage-service --cluster jfp-ecs-cluster-stage
