# Workflow name
name: Chromatic Deployment

# Event for the workflow
on: [push, pull_request]

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - name: Build affected storybooks for VR
        run: npm run affected:build-storybook -- --base=$GITHUB_BASE_REF
        #👇 Adds Chromatic as a step in the workflow
      - name: Run VR tests 
        uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: 'dist/storybook'


          # .github/workflows/chromatic.yml