name: Stage Merge
on:
  push:
    branches:
      - add-ns3-serverless
#on:
#  push:
#    branches:
#      - stage
jobs:
  build-and-deploy:
    environment: Preview
    runs-on: ubuntu-latest
    env:
      ENV_SUFFIX: stage
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: NPM Install
        run: npm install

      - name: Install Serverless
        run: npm install -g serverless

      - name: Deploy/Update Infrastructure
        run: serverless deploy --config resources/cf-stacks/serverless.yml --env $ENV_SUFFIX

      - name: Run NX generate and build
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: prismagenerate,deploy
          projects: api-journeys

      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Allow Github Actions Access to Postgres
        run: aws ec2 authorize-security-group-ingress --group-id sg-09be37cc196b4b4c6 --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Prisma Migrations api-journeys
        run: npx prisma migrate deploy --schema apps/api-journeys/prisma/schema.prisma

      - name: Seed DB
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: seed
          projects: api-journeys

      - name: Remove Github Actions Access to Postgres
        run: aws ec2 revoke-security-group-ingress --group-id sg-09be37cc196b4b4c6 --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
