name: Stage Merge
on:
  push:
    branches:
      - add-ns3-serverless
#on:
#  push:
#    branches:
#      - stage

jobs:
  build-and-deploy:
    environment: Stage
    env:
      ENV_SUFFIX: stage
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: NPM Install
        run: npm install

      - name: Install Serverless
        run: npm install -g serverless

      - name: Install Rover
        run: npm install -g @apollo/rover

      # - name: Deploy/Update Infrastructure
      #   run: serverless deploy --config resources/cf-stacks/serverless.yml --env $ENV_SUFFIX

      - name: Deploy/Update Infrastructure
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: deploy
          projects: infrastructure
          args: --config resources/cf-stacks/serverless.yml --env $ENV_SUFFIX

      - name: Run NX generate and deploy lambdas
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: prismagenerate,deploy
          projects: api-journeys

      - name: Get api-journeys endpoint
        run: |
          JOURNEY_API_ENDPOINT=$( jq '.endpoints.GET' journeys-output.json )

      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Allow Github Actions Access to Postgres
        run: aws ec2 authorize-security-group-ingress --group-name ark-weave-postgres-$ENV_SUFFIX --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Prisma Migrations api-journeys
        run: npx prisma migrate deploy --schema apps/api-journeys/prisma/schema.prisma

      - name: Seed DB
        run: npx prisma db seed --preview-feature --schema apps/api-journeys/prisma/schema.prisma

      - name: Publish Apollo Graph
        run: rover subgraph publish ark-weave-journeys@preprod --name journeys --schema apps/api-journeys/schema.graphql --routing-url https://q2hqgdvfmk.execute-api.us-east-1.amazonaws.com/dev/journeys

      # Cleanup / remove Github access to postgres.
      - name: Remove Github Actions Access to Postgres
        if: always()
        run: aws ec2 revoke-security-group-ingress --group-name ark-weave-postgres-$ENV_SUFFIX --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
