name: watch-monitoring-every3mins
on:
  schedule:
    - cron: '*/3 * * * *'
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test apps/watch-e2e/src/monitoring/monitor.spec.ts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: watch-monitoring
          path: |
            playwright-report/
          retention-days: 5
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#apps-monitoring'
          message: watch app (https://www.jesusfilm.org/watch) is down.
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
