name: Worker Deploy

on:
  push:
    branches: [main, stage]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  affected:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    strategy:
      matrix:
        node-version: [22]
    env:
      PNPM_STORE_PATH: $HOME/.pnpm-store
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Mount pnpm store (stickydisk)
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-pnpm-store-${{ runner.os }}
          path: $HOME/.pnpm-store
      - name: Configure pnpm store-dir
        run: pnpm config set store-dir $HOME/.pnpm-store
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --silent
      - uses: nrwl/nx-set-shas@v4
      - id: set-matrix
        name: set matrix worker to affected array
        run: |
          matrix=$(pnpm -s exec ts-node tools/scripts/deploy-apps.ts --projects workers/*)
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  deploy-stage:
    name: Deploy Stage
    needs: affected
    if: |
      needs.affected.outputs.matrix != '[]' &&
      needs.affected.outputs.matrix != '' &&
      github.ref == 'refs/heads/stage'
    strategy:
      fail-fast: false
      matrix:
        app: ${{fromJson(needs.affected.outputs.matrix)}}
        github-ref-name: ['${{ github.ref_name }}']
        node-version: [22]
    runs-on: blacksmith-2vcpu-ubuntu-2204
    env:
      PNPM_STORE_PATH: $HOME/.pnpm-store
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Mount pnpm store (stickydisk)
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-pnpm-store-${{ runner.os }}
          path: $HOME/.pnpm-store
      - name: Configure pnpm store-dir
        run: pnpm config set store-dir $HOME/.pnpm-store
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --silent
      - uses: nrwl/nx-set-shas@v4
      - name: worker deployment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: pnpm exec nx run-many --target=deploy --projects=${{ matrix.app }}

  deploy-production:
    name: Deploy Production
    needs: affected
    if: |
      needs.affected.outputs.matrix != '[]' &&
      needs.affected.outputs.matrix != '' &&
      github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        app: ${{fromJson(needs.affected.outputs.matrix)}}
        github-ref-name: ['${{ github.ref_name }}']
        node-version: [22]
    runs-on: blacksmith-2vcpu-ubuntu-2204
    env:
      PNPM_STORE_PATH: $HOME/.pnpm-store
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Mount pnpm store (stickydisk)
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-pnpm-store-${{ runner.os }}
          path: $HOME/.pnpm-store
      - name: Configure pnpm store-dir
        run: pnpm config set store-dir $HOME/.pnpm-store
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --silent
      - uses: nrwl/nx-set-shas@v4
      - name: worker deployment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        run: pnpm exec nx run-many --target=deploy --projects=${{ matrix.app }} --prod
